name: checks
on: [push, pull_request]
jobs:
  test:
    name: test py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install ".[tests]"

      - name: Run tests
        run: python3 -m pytest

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python3 -m pip install ".[dev]"

      - name: Check style
        run: python3 -m ruff check . && python3 -m ruff format --check .

  precommit_hooks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        hook:
          - name: "Check EOF format"
            args: "end-of-file-fixer --all-files"
          - name: "Check trailing whitespace"
            args: "trailing-whitespace --all-files"
          - name: "Check line ending format"
            args: "mixed-line-ending --fix=lf --all-files"
    steps:
      - uses: actions/checkout@v3

      - name: ${{ matrix.hook.name }}
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: ${{ matrix.hook.args }}


  docs:
    runs-on: ubuntu-latest
    env:
      SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install '.[docs]'

      - name: Attempt docs build
        working-directory: ./docs
        run: make html

